name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build backend
        run: npm run build:backend

      - name: Build frontend
        run: npm run build

      - name: Prepare icons
        run: npm run prepare-icons

      # Set up Wine for Windows builds on Linux (if cross-building Windows from Ubuntu)
      - name: Set up Wine (for Windows targets on Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y wine64

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: npm run dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: |
            # Linux artifacts (AppImage, deb)
            dist/*.AppImage
            dist/*.deb
            # Windows artifacts (exe, msi, portable)
            dist/*.exe
            dist/*.msi
            dist/*.portable.exe
            # macOS artifacts (dmg, zip)
            dist/*.dmg
            dist/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
          token: ${{ secrets.PAT_TOKEN }}
